### ISSUE TITLE
Remove sender semantics

### ISSUE THREAD

**Issue by robinwhittleton** [bob-reus/joris-karl-huysmans_against-the-grain#10]
https://github.com/bob-reus/joris-karl-huysmans_against-the-grain/blob/63cdfab7657fadbc0e48adc899525b78c360f616/src/epub/text/preface.xhtml#L91

Sorry, one last fix: `z3998:sender` semantics are specifically for letters. We can remove that (and keep `z3998:signature`).

**Comment by bob-reus** [comment]
Removed z3998:sender :)
