### ISSUE TITLE
Grab bag of preface issues

### ISSUE THREAD

**Issue by robinwhittleton** [bob-reus/joris-karl-huysmans_against-the-grain#3]
- [x] Missing accents from ‘À’ in ‘A vau-l’eau’, ‘A Rebours’
- [x] Missing xml:lang="fr" from ‘À rebours’
- [x] ‘Le Roman Contemporain’ is a book
- [x] ‘Chapter VII’ can be a hyperlink to that chapter
- [x] ‘Là-Bas’ missing book semantics in one case
- [x] ‘After such a book’ paragraph should probably be in a blockquote.
- [x] Huysman’s name at the end should be in a footer with appropriate styling (https://standardebooks.org/manual/1.7.0/single-page#7.7.3.2) and with signature semantics and styling (https://standardebooks.org/manual/1.7.0/single-page#7.7.3.4). Remove the hard capitalisation, the styling will provide small-caps. The date can be on its own paragraph inside the footer.

**Comment by bob-reus** [comment]
All fixed :)
