### ISSUE TITLE
Non-English diphthongs should generally be retained

### ISSUE THREAD

**Issue by robinwhittleton** [bob-reus/joris-karl-huysmans_against-the-grain#4]
https://github.com/bob-reus/joris-karl-huysmans_against-the-grain/blob/4fe91010986fc82d4fa5077179307863a998b544/src/epub/text/chapter-1.xhtml#L40

`oeil-de-boeuf` here should be `œil-de-bœuf`. I guess there could be other occurrences of similar words but I haven’t scanned for them.

**Comment by bob-reus** [comment]
Fixed in this and one other occurrence.
