### ISSUE TITLE
Potential elision in verse

### ISSUE THREAD

**Issue by robinwhittleton** [bob-reus/joris-karl-huysmans_against-the-grain#7]
https://github.com/bob-reus/joris-karl-huysmans_against-the-grain/blob/4fe91010986fc82d4fa5077179307863a998b544/src/epub/text/chapter-14.xhtml#L70

Is this line an elision? If so then we have a specific way to treat those: https://standardebooks.org/manual/1.7.0/single-page#7.5.7

**Comment by bob-reus** [comment]
It's elision: https://www.gutenberg.org/files/15112/15112-h/15112-h.htm#jn2 (poem ART POÉTIQUE). 

I have changed the line accordingly.
