### ISSUE TITLE
Use right double quote for ditto marks

### ISSUE THREAD

**Issue by robinwhittleton** [bob-reus/joris-karl-huysmans_against-the-grain#8]
https://github.com/bob-reus/joris-karl-huysmans_against-the-grain/blob/4fe91010986fc82d4fa5077179307863a998b544/src/epub/text/chapter-15.xhtml#L59-L64

At the moment these are left double quotes, but should be right double quotes: https://standardebooks.org/manual/1.7.0/single-page#8.7.5.4

**Comment by bob-reus** [comment]
Fixed
